(declare (uses ltg-proto))
(declare (uses ltg-cards))
(declare (uses ltg-stack))
(display-player-states players)
(set! players (car (eval-slot-to-card players 0 K)))
(set! players (car (eval-slot-to-card players 0 dec)))
(set! players (car (eval-card-to-slot players S 0)))
(set! players (car (eval-slot-to-card players 0 succ)))
(set! players (player-field! (player-vitality! players 1 0 -1) 1 255 (make-r-stack-item "255" val 1 255)))
(display-player-states players)
(go read-action-type players)

(if (and (string=? (stack-item-desc (player-field players 0 0))
									 "I")
				 (equal? (player-vitality players 1 0)
								 -1))
		(printf "PASS\n")
		(printf "FAIL\n"))
